<a href="https://colab.research.google.com/github/rahulcheeti/machine-learning/blob/master/hw1prog3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This code is not able to update Weights in back-propagation modulue....All the best if you can fix it and make it run

In [0]:
import keras
import numpy as np
from keras.datasets import mnist
import math

lear_rate = 0.005
batch_size = 100
experiments = 40

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = (x_train.reshape(x_train.shape[0],x_train.shape[1]*x_train.shape[2]))
#y_train = (keras.utils.to_categorical(y_train,10))

x_test = (x_test.reshape(x_test.shape[0],x_test.shape[1]*x_test.shape[2]))
y_te = y_test
y_test = (keras.utils.to_categorical(y_test,10))

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

In [0]:
def initialize_parameters():
  W = abs(np.random.randn(10,784)*0.01)
  b = abs(np.random.randn(10,1)*0.01)
  return W,b

In [0]:
def forward_propagation(W,b,x):
  output = (np.transpose(np.dot(W,np.transpose(x)) + b))
  summation = 0
  eps = 0.00001
  for i in range(len(x)):
    summation = 0
    for j in range(len(output[1])):
      summation += np.exp(output[i][j]) + eps
    output[i] = np.exp(output[i])/summation
  output = np.transpose(output)
  return output

In [113]:
W,b = initialize_parameters()
output = forward_propagation(W,b,x_train[0:20])
print(W)
W,b = backward_propagation(x_train[0:20],y_train[0:20],output,W,b,lear_rate,batch_size)
print(W)
output = forward_propagation(W,b,x_train[0:20])
output = abs(output)

[[0.00656409 0.00933824 0.00244751 ... 0.00513231 0.01721452 0.00588277]
 [0.00903868 0.00214392 0.01016364 ... 0.00858687 0.00702496 0.00345712]
 [0.013738   0.02290493 0.01445875 ... 0.00678036 0.00097187 0.00755343]
 ...
 [0.00837847 0.00793448 0.00275715 ... 0.01206173 0.01014607 0.00446139]
 [0.00090516 0.0071681  0.00306473 ... 0.00079337 0.01478636 0.0059363 ]
 [0.00597226 0.0122195  0.00329775 ... 0.03145784 0.00234045 0.00220187]]
[[0.00656409 0.00933824 0.00244751 ... 0.00513231 0.01721452 0.00588277]
 [0.00903868 0.00214392 0.01016364 ... 0.00858687 0.00702496 0.00345712]
 [0.013738   0.02290493 0.01445875 ... 0.00678036 0.00097187 0.00755343]
 ...
 [0.00837847 0.00793448 0.00275715 ... 0.01206173 0.01014607 0.00446139]
 [0.00090516 0.0071681  0.00306473 ... 0.00079337 0.01478636 0.0059363 ]
 [0.00597226 0.0122195  0.00329775 ... 0.03145784 0.00234045 0.00220187]]


In [0]:
def loss_function(y_train,output,batch_size):
  loss = np.sum(np.multiply((np.transpose(y_train) - output),(np.transpose(y_train) - output))/2,axis=1,keepdims=True)/batch_size
  return loss

In [0]:
def backward_propagation(x_train,y_train,output,W_a,b_a,lear_rate,batch_size):
  #print(output.shape)
  #der_bet = output - np.transpose(y_train)
    #print(der_bet)
    #der_bet = np.sum(abs(der_bet, axis = 0, keepdims = True)
    #print(der_bet)
    #der_bet = der_bet
    #print(der_bet)
  #der_z = der_bet
  #print(der_z)
  #der_W = np.dot(der_z,x_train)
  #der_b = np.sum(der_z, axis =1 ,keepdims = True)
  #print(der_W.shape)
  #print(der_W)
  #print(der_b)
  der_loss = output - np.transpose(y_train)
  der_W = np.dot(der_loss,x_train)
  der_b = np.sum(der_loss,axis=1,keepdims=True)
  W_a = W_a - (lear_rate*der_W)
  b_a = b_a - lear_rate*der_b
  #print(W)
  #print(b)
  return W_a, b_a

In [115]:
W,b = initialize_parameters()
output = forward_propagation(W,b,x_train[0:60000])
W,b = backward_propagation(x_train[0:60000],y_train[0:60000],output,W,b,lear_rate,batch_size)
out = forward_propagation(W,b,x_test)
out = np.transpose(out)
out_list = []

for i in range(10000):
  out_list.append(np.argmax(out[i]))
count = 0
for i in range(10000):
  if out_list[i] == y_te[i]:
    count += 1
out_list = []
acc = count/100
print(count,"/10000")
print("accuracy:",acc)


980 /10000
accuracy: 9.8


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: overflow encountered in exp
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


In [114]:
W,b = initialize_parameters()
for j in range(experiments):
  for i in range(0, len(x_train), batch_size):
    output = forward_propagation(W,b,x_train[i:i+batch_size])
    W,b = backward_propagation(x_train[i:i+batch_size],y_train[i:i+batch_size],output,W,b,lear_rate,batch_size)
    #output = forward_propagation(W,b,x_train[0:60000])
    #W,b = backward_propagation(x_train[0:60000],y_train[0:60000],output,W,b,lear_rate,batch_size)
  out = forward_propagation(W,b,x_test)
  out = np.transpose(out)
  out_list = list()
  for i in range(10000):
    out_list.append(np.argmax(out[i]))
  count = 0
  for i in range(10000):
    if out_list[i] == y_te[i]:
      count += 1
  out_list = []
  acc = count/100
  print("epoch:",j)
  print(count,"/10000")
  print("accuracy:",acc)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: overflow encountered in exp
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


epoch: 0
980 /10000
accuracy: 9.8
epoch: 1
980 /10000
accuracy: 9.8


KeyboardInterrupt: ignored

In [107]:
W,b = initialize_parameters()
for j in range(experiments):
  #for i in range(0, len(x_train), batch_size):
    #output = forward_propagation(W,b,x_train[i:i+batch_size])
    #W,b = backward_propagation(x_train[i:i+batch_size],y_train[i:i+batch_size],output,W,b,lear_rate,batch_size)
  output = forward_propagation(W,b,x_train[0:60000])
  W,b = backward_propagation(x_train[0:60000],y_train[0:60000],output,W,b,lear_rate,batch_size)
  out = forward_propagation(W,b,x_test)
  out = np.transpose(out)
  out_list = []
  for i in range(10000):
    out_list.append(np.argmax(out[i]))
  count = 0
  for i in range(10000):
    if out_list[i] == y_te[i]:
      count += 1
  out_list = []
  acc = count/100
  print("epoch:",j)
  print(count,"/10000")
  print("accuracy:",acc)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: overflow encountered in exp
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


epoch: 0
980 /10000
accuracy: 9.8
epoch: 1
980 /10000
accuracy: 9.8


KeyboardInterrupt: ignored